name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Deploy to GitHub Pages
        run: |
          cd dist
          git init
          git branch -m gh-pages
          git config user.email "black00731@gmail.com"
          git config user.name "BlaChalk"
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/BlaChalk/WeatherForecast.git gh-pages
